title: Jani Krašovec
description: Personal website and notes
remote_theme: "mmistakes/minimal-mistakes@4.26.2"   # very popular in 2026
plugins:
  - jekyll-remote-theme

show_excerpts: true

# Optional but useful
github_username: JaniKrasovec
